In [1]:
import pandas as pd

In [3]:
hotels = pd.read_csv("../../datasets/hotels_athens.csv")
reviews = pd.read_csv("../../datasets/reviews_athens.csv")

### Preprocess 'hotels_athens.csv'

In [4]:
hotels.head()

,place_id,name,rating,address
0,ChIJYbMf-s-joRQRrfrtIL4BKQo,LoftLiving,NaN,"Agias Grigorousas 42, Chaidari"
1,ChIJXa9EhZajoRQRvI6l9_rat1U,ChrisAndro Apartments,4.7,"Pipinou 45, Athina"
2,ChIJiXeczKukoRQR5As1xN5u7Yo,NEFELI SA,NaN,"Aidiniou 21, Chaidari"
3,ChIJiXeczKukoRQRP-j3EeDy8Rc,ΑΠΕΡΑΝΤΟ ΓΑΛΑΖΙΟ,5.0,"Aidiniou 21, Chaidari"
4,ChIJm9S4QVSjoRQR6fPtkkjJ_8I,Camping Athens,3.4,"Leoforos Athinon 198-200, Athina"

In [5]:
hotels.count()

place_id    2645
name        2645
rating      1848
address     2644
dtype: int64

In [17]:
hotels.duplicated().value_counts()

True     1379
False    1266
Name: count, dtype: int64

In [24]:
hotels.drop_duplicates(inplace=True)
hotels.dropna(inplace=True)
hotels.count()

place_id    874
name        874
rating      874
address     874
dtype: int64

### Preprocess 'reviews_athens.csv'

In [6]:
reviews.head()

,place_id,author_name,rating,text,time
0,ChIJXa9EhZajoRQRvI6l9_rat1U,Arthur Quing,5,Feels like I'm home. Our family loves the swim...,a year ago
1,ChIJXa9EhZajoRQRvI6l9_rat1U,M. K.,5,This is a hidden gem in the city. Great overni...,10 months ago
2,ChIJXa9EhZajoRQRvI6l9_rat1U,Stefhanie de Kom,5,Very nice people. I was there just to visit my...,4 years ago
3,ChIJXa9EhZajoRQRvI6l9_rat1U,yoel guenine,5,Amazing appartment full equipped.,3 years ago
4,ChIJXa9EhZajoRQRvI6l9_rat1U,Kostas Gontikakis,5,The best place in Athens!,3 years ago

In [7]:
reviews.count()

place_id       7506
author_name    7506
rating         7506
text           6618
time           7506
dtype: int64

In [14]:
reviews.duplicated().value_counts()

True     3986
False    3520
Name: count, dtype: int64

In [23]:
reviews.drop_duplicates(inplace=True)
reviews.dropna(inplace=True)
reviews.count()

place_id       3072
author_name    3072
rating         3072
text           3072
time           3072
dtype: int64